version: '2'
services:
  app:
    build:
      context: ./
    environment:
      - EMAIL_TARGET=${EMAIL_TARGET}
      - CURRENCIES=${CURRENCIES}
      - MAILGUN_KEY=${MAILGUN_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
    volumes:
      - ./:/crypto-ticker/
    ports:
      - "3100:3100"

volumes:
  timecapsule-mysqldata:
    driver: "local"